name: Run Python Script
on: [push] # 触发条件（如代码推送时运行）

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 指定 Python 版本
      - name: Run Script
        run: python exam_webui.py
